name: Publish Docker Image to Dockerhub

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'app.js'
      - 'routes/**'
      - 'db.js'
      - 'Dockerfile'
      - 'package*.json'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: amosgantian/nav-item-backend:latest
